"use client";
import './globals.css';
import type { Metadata } from 'next';
import { League_Spartan } from 'next/font/google';
import { Dispatch, SetStateAction, createContext, useState } from 'react';
import Header from '@/components/ui/header';
import Footer from '@/components/ui/footer';


const league_Spartan = League_Spartan({subsets: ['latin'], weight: ['200','300','500','700']});

export const metadata: Metadata = {
  title: 'HireDEV',
  description: 'Generated by create next app',
}

interface filterContextProps {
  region: string | null;
  contract: string | null;
  tool: string | null;
}
const defaultFilterState = {
  region: null,
  contract: null,
  tool: null
} as filterContextProps;

export const filterContext = createContext(defaultFilterState);

interface setFilterContextProps {
  setRegion: Dispatch<SetStateAction<string | null>>;
  setContract: Dispatch<SetStateAction<string | null>>;
  setTool: Dispatch<SetStateAction<string | null>>;
} 

const defaultFilterFunctions = {
  setRegion: () => {},
  setContract: () => {},
  setTool: () => {},
} as setFilterContextProps;

export const setFilterContext = createContext(defaultFilterFunctions);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [region, setRegion] = useState<string | null>(null);
  const [contract, setContract] = useState<string | null>(null);
  const [tool, setTool] = useState<string | null>(null);
  return (
    <html lang="en" className="bg-cyan-100">
      <body className={league_Spartan.className}>
        <div className="w-full bg-cyan-100">
          <setFilterContext.Provider value={{setRegion, setContract, setTool}}>
            <filterContext.Provider value={{region, contract, tool}}>


                <Header />
                {children}
                <Footer />



                
            </filterContext.Provider>
          </setFilterContext.Provider>
        </div>
      </body>
    </html>
  )
}
